Controllers/ge_agsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Microsoft.AspNetCore.Mvc;
using ge_repository.Models;
using ge_repository.Extensions;

namespace ge_repository.Controllers 
{

    public class ge_agsController : Controller
    {
  	private readonly ge_DbContext _context;
        public  ge_agsController (ge_DbContext context)
        {
            _context = context;
        }        
        public ActionResult Create(Guid ge_data)
        {
            // check connection setting to ags_server

            // get ge_data
            
            // check is ags format

            // initialise and load ags_client
            
            // start ags_client thread to send to ags_server

            // await for completed repsonse?
            

            ViewData["Message"] = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult Index()
        {
            ViewData["Message"] = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Controllers/ge_fileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ge_repository.Models;
using ge_repository.Extensions;

namespace ge_repository.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ge_fileController: ControllerBase       
    
    {
    private readonly ge_DbContext _context;

        public ge_fileController(ge_DbContext context)
        {
            _context = context;
        }
       
 [HttpGet("{id}")]
 
    public async Task<IActionResult> Get(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var _data_big = await _context.ge_data_big.SingleOrDefaultAsync(m => m.Id == id);
            
            if (_data_big == null)
            {
                return NotFound();
            }

            var _data = await _context.ge_data.SingleOrDefaultAsync(m => m.Id == id);

            var ContentType = _data.GetContentType();
            var filename = _data.filename;
            MemoryStream memory = _data_big.getMemoryStream();

            return File(memory, ContentType, filename);

            }
   [HttpPost]

   public async Task<IActionResult> Post([FromForm] fileUpload data) {
          
            if (data.files == null) {
                throw new ArgumentNullException(nameof(data.files));
            }
            if (data.projectId == null) {
                throw new ArgumentNullException(nameof(data.files));
            }

            var ge_project = await _context.ge_project.FindAsync(data.projectId);

            if (ge_project == null) {
                return NotFound();
            } 
            
            long size = data.files.Sum(f => f.Length);

            // full path to file in temp location
            var filePath = Path.GetTempFileName();

            foreach (var uploadFile in data.files) {
                if (uploadFile.Length > 0) {

                    Boolean IsBinary = uploadFile.IsContentTypeBinary(ModelState);
                    var ge_data_big = new ge_data_big();
                    var ge_data = new ge_data ();
    
                    if (IsBinary) { 
                        ge_data_big.data_binary = await uploadFile.ProcessFormFileBinary( ModelState);
                    }  else {
                        ge_data_big.data_string = await uploadFile.ProcessFormFileString( ModelState);
                    }
                    // Perform a second check to catch ProcessFormFile method violations.
                    if (!ModelState.IsValid) {
                        return NotFound();
                    }
                    ge_data.projectId = ge_project.Id;
                    ge_data.locEast = ge_project.locEast;
                    ge_data.locNorth = ge_project.locNorth;
                    // Add deatils of uploaded file to new _ge_data record
                    ge_data.data = ge_data_big;
                    ge_data.filesize = uploadFile.Length; 
                    ge_data.filename = uploadFile.FileName; 
                    ge_data.createdDT = DateTime.UtcNow;
                    // ge_data.ownerId = User.
                    _context.ge_data.Add(ge_data);
                    await _context.SaveChangesAsync();
                }
            }

            // process uploaded files
            // Don't rely on or trust the FileName property without validation.

            return Ok();
        } 
 

    }
}

Pages/Data/Create.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

using ge_repository.Models;
using ge_repository.Authorization;
using ge_repository.Pages.Shared;
using ge_repository.Extensions;
using ge_repository.DAL;

namespace ge_repository.Pages.Data
{
    public class CreateModel : DI_BasePageModel
    {   
              
        [BindProperty]
        public ge_data data {get;set;}
        
        [BindProperty]
        [Required]
        [Display(Name="Upload Files")]

         public IList<IFormFile> uploadFiles { get; set; }
        
        [BindProperty]
        public string LastModifiedDates {get;set;}

        public CreateModel(

            ge_DbContext context,
            IAuthorizationService authorizationService,
            UserManager<ge_user> userManager)
            : base(context, authorizationService, userManager)
        {
           
        }

      public async Task<IActionResult> OnGetAsync(Guid projectId)
        {
             if (projectId == null) {
                return NotFound();
            }
        
            var project = await _context.projectFull(projectId).FirstOrDefaultAsync();

            if (project == null) {
                return NotFound();
            }
            
            var UserId = _userManager.GetUserId(User);
          
            Boolean CanCreate = _context.IsProjectOperationAllowed("Create", project, UserId);
            
            if (!CanCreate) {
               return RedirectToPageMessage (msgCODE.DATA_CREATE_PROHIBITED);
            }
            
            ViewData["ProjectName"] =  project.name;
            
            data = new ge_data();
            
            data.locEast=  project.locEast;
            data.locNorth = project.locNorth;
            data.locLevel = project.locLevel;

            data.locName = project.locName;
            data.locAddress = project.locAddress;
            data.locPostcode = project.locPostcode;

            data.locLatitude =project.locLatitude;
            data.locLongitude =project.locLongitude;
            data.locHeight = project.locHeight;

            data.locMapReference = project.locMapReference;
            data.datumProjection=project.datumProjection;

            data.projectId = project.Id;

            return Page();

        } 


    public async Task<IActionResult> OnPostAsync()
    {
        
            if (!ModelState.IsValid) {
               return Page();
            }
            
            var project = await _context.projectFull(data.projectId).FirstOrDefaultAsync();

            var userId = _userManager.GetUserId(User);
          
            Boolean CanCreate = _context.IsProjectOperationAllowed("Create", project, userId);
            
           if (!CanCreate) {
              RedirectToPageMessage(msgCODE.DATA_CREATE_PROHIBITED);
            }

            ProjectionSystem ps = new ProjectionSystem();
            ige_projectionDAL pd = ps.getProjectionDAL(data);
            
            if (!pd.updateAll()) {
                ViewData["CoordinateMessage"] = pd.getMessage();
                return Page();
            }
            
           
            string[] lastmodified = LastModifiedDates.Split(";");
            int i = 0;

            foreach (var formFile in uploadFiles)
                {
                    Boolean IsBinary = formFile.IsContentTypeBinary(ModelState);
                    
                    ge_data_big b = new ge_data_big();
                    ge_data d = new ge_data();

                    d.createdId = _userManager.GetUserId(User);    
                    
                    if (IsBinary) { 
                        b.data_binary = await formFile.ProcessFormFileBinary( ModelState);
                    }  else {
                        b.data_string = await formFile.ProcessFormFileString( ModelState);
                    }

                    // Perform a second check to catch ProcessFormFile method
                    // violations.
                    if (!ModelState.IsValid) {
                    return Page();
                    }
                    
                    d.projectId = project.Id;

                    d.locEast = data.locEast;
                    d.locNorth = data.locNorth;
                    d.locLevel = data.locLevel;

                    d.locLatitude = data.locLatitude;
                    d.locLongitude =data.locLongitude;
                    d.locHeight = data.locHeight;
                    
                    d.locMapReference = data.locMapReference;
                    d.locName = data.locName;
                    d.locAddress = data.locAddress;
                    d.locPostcode = data.locPostcode;
                    
                    d.datumProjection = data.datumProjection ;

                    d.description = data.description;
                    d.keywords = data.keywords;
                    
                    // Add deatils of uploaded file to new _ge_data record
                    d.data = b ;
                    d.filesize = formFile.Length; 
                    d.filename = formFile.FileName;
                    d.fileext = formFile.FileExtension();
                    d.filetype = formFile.ContentType;
                
                    d.filedate = Convert.ToDateTime(lastmodified[i]);
                    d.createdId = userId;
                    d.createdDT = DateTime.UtcNow;
                
                    _context.ge_data.Add(d);
                    
                
            }
   
            await _context.SaveChangesAsync();
            
            return RedirectToPage("./Index",new {pageProjectId=project.Id});
    } 

    }
}

Pages/Data/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ge_repository.Models;

namespace ge_repository.Pages.Data
{
    public class DeleteModel : PageModel
    {
        private readonly ge_repository.Models.ge_DbContext _context;

        public DeleteModel(ge_repository.Models.ge_DbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ge_data Data { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Data = await _context.ge_data.SingleOrDefaultAsync(m => m.Id == id);

            if (Data == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Data = await _context.ge_data.FindAsync(id);

            if (Data != null)
            {
                _context.ge_data.Remove(Data);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Data/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

using ge_repository.Models;
using ge_repository.Authorization;
using ge_repository.Pages.Shared;
using ge_repository.Extensions;

namespace ge_repository.Pages.Data
{
    public class DetailsModel : DI_BasePageModel
    {
        public DetailsModel(

            ge_DbContext context,
            IAuthorizationService authorizationService,
            UserManager<ge_user> userManager)
            : base(context, authorizationService, userManager)
        {
           
        }
        public ge_data data { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null) {
                return NotFound();
            }

            data = await _context.ge_data
                .Include(g => g.edited)
                .Include(g => g.created)
                .Include(g => g.project).FirstOrDefaultAsync(m => m.Id == id);

            if (data == null) {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);

            bool CanRead =_context.IsDataOperationAllowed("Read",data,data.project,userId);
            if (!CanRead) {
                RedirectToPageMessage (msgCODE.DATA_READ_PROHIBITED);
            }

            return Page();
        }
    }
}

Pages/Data/Download.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Text.Encodings;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ge_repository.Models;

namespace ge_repository.Pages.Data
{
    public class DownloadModel : PageModel
    {
        private readonly ge_repository.Models.ge_DbContext _context;

        public DownloadModel(ge_repository.Models.ge_DbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ge_data_big _data_big { get; set; }
        public ge_data _data { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _data_big = await _context.ge_data_big.SingleOrDefaultAsync(m => m.Id == id);
            
            if (_data_big == null)
            {
                return NotFound();
            }

            _data = await _context.ge_data.SingleOrDefaultAsync(m => m.Id == id);

            var filetype = _data.filetype;
            var filename = _data.filename;
            MemoryStream memory = _data_big.getMemoryStream();

            return File(memory, filetype, filename);

            }
                       

/*         public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Data = await _context.ge_data.FindAsync(id);

            if (Data != null)
            {
                _context.ge_data.Remove(Data);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }


         public async Task<IActionResult> Download(string filename)
        {
            if (filename == null)
                return Content("filename not present");

            var path = Path.Combine(
                           Directory.GetCurrentDirectory(),
                           "wwwroot", filename);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path)); */
        }
}

Pages/Data/Create.cshtml
@page
@model ge_repository.Pages.Data.CreateModel

@{
    ViewData["Title"] = "Create";
}
<h2>Add Data</h2>
<h2>
    @ViewData["ProjectName"] 

</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="data.Id" />
            <input type="hidden" asp-for="data.projectId" />
            <input type="hidden" asp-for="data.createdDT"/>
            <input type="hidden" asp-for="data.createdId"/>
            <input type="hidden" asp-for="data.editedDT"/>
            <input type="hidden" asp-for="data.editedId"/> 
            <partial name="_inputData"
                    for="data"
                    view-data="ViewData" />
            <partial name="_inputLocation"
                    for="data"
                    view-data="ViewData" />
            <div id="drop-area" class="form-group"
                    ondragenter="event.stopPropagation(); event.preventDefault();" 
                    ondragover="event.stopPropagation(); event.preventDefault();" 
                    ondrop="event.stopPropagation(); event.preventDefault();dodrop(event);">
                <p>Upload multiple files with the file dialog or by dragging and dropping images onto the dashed region</p>
                <div class="form-group">
                    <label class="control-label">Selected Files</label>
                    <ol id=selectedFiles></ol>
                    <span asp-validation-for="uploadFiles" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="uploadFiles" class="control-label"></label>
                    <input asp-for="uploadFiles" type="file" name=uploadFiles multiple class ="form-control" style="height:auto" onchange=updateSelectedFiles()/>
                    <input type="hidden" asp-for="LastModifiedDates" />
                    <span asp-validation-for="uploadFiles" class="text-danger"></span>
                </div>              
                </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
        
    </div>
</div>
<iframe id=googlemap 
src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=Malet%20St%2C%20London%20WC1E%207HU%2C%20United%20Kingdom+(Your%20Business%20Name)&ie=UTF8&t=&z=14&iwloc=B&output=embed" 
frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
</iframe>

<div>
    <a asp-page="Index">Back to List</a>
</div>

 

Pages/Data/Delete.cshtml
@page "{id:Guid}"
@model ge_repository.Pages.Data.DeleteModel

@{
    ViewData["Title"] = "Delete GE Data";
}

<h2>Delete GE Data</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Data.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Data.filesize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.filesize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Data.filename)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.filename)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Data.createdDT)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.createdDT)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Data.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Data/Details.cshtml
@page
@model ge_repository.Pages.Data.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ge_data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.data.filename)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.filename)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.filesize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.filesize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.filetype)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.filetype)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.filedate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.filedate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.keywords)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.keywords)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.project.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.project.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.cstatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.cstatus)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.pstatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.pstatus)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.data.qstatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data.qstatus)
        </dd>
        <partial name="_DetailsLocation"
                    for="data"
                    view-data="ViewData" />
        <partial name="_DetailsBase"
                    for="data"
                    view-data="ViewData" />
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.data.Id">Edit</a>
    @if (@Model.data.fileext == ".ags") {
                <text> | </text>
                <a asp-controller="ge_ags" asp-action="Get" asp-route-id=@Model.data.Id>Create XML</a>
    }
    @if (@Model.data.fileext == ".xml") {
                <text> | </text>
                <a asp-page="../Transform/Create" asp-route-id="@Model.data.project.Id">Create Transform</a>
    }
    | <a asp-page="./Index">Back to List</a>
</div>

Pages/Data/Download.cshtml
@page "{id:Guid}"
@model ge_repository.Pages.Data.DeleteModel

@{
    ViewData["Title"] = "Delete GE Data";
}

<h2>Delete GE Data</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Data.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Data.filesize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.filesize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Data.filename)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.filename)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Data.createdDT)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Data.createdDT)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Data.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Data/Edit.cshtml
@page
@model ge_repository.Pages.Data.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>data</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="data.Id" />
            <input type="hidden" asp-for="data.projectId" />
            <input type="hidden" asp-for="data.createdDT"/>
            <input type="hidden" asp-for="data.createdId"/>
            <input type="hidden" asp-for="data.editedDT"/>
            <input type="hidden" asp-for="data.editedId"/>    
           <partial name="_inputData"
                    for="data"
                    view-data="ViewData" />
            <div class="form-group">
                <label asp-for="data.filename" class="control-label"></label>
                <input asp-for="data.filename" class="form-control" readonly/>
                <span asp-validation-for="data.filename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data.filesize" class="control-label"></label>
                <input asp-for="data.filesize" class="form-control" readonly/>
                <span asp-validation-for="data.filesize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data.fileext" class="control-label"></label>
                <input asp-for="data.fileext" class="form-control" readonly/>
                <span asp-validation-for="data.fileext" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data.filetype" class="control-label"></label>
                <input asp-for="data.filetype" class="form-control" readonly/>
                <span asp-validation-for="data.filetype" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data.filedate" class="control-label"></label>
                <input asp-for="data.filedate" class="form-control" readonly/>
                <span asp-validation-for="data.filedate" class="text-danger"></span>
            </div>
           <partial name="_inputLocation"
                    for="data"
                    view-data="ViewData" />
           <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
           </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>


Pages/Data/Index.cshtml
@page
@model ge_repository.Pages.Data.IndexModel

@{
    ViewData["Title"] = "Ground Engineering Data";
}
<h2>Index</h2>

<form asp-page="./Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search: <input type="text" name="pageFilter" value="@(Model.pageFilter)" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-page="./Index">Back to full List</a>
        </p>
    </div>
</form>
    @if (@Model.pageProjectId !=null) {
        <p>
        @Model._ge_data[0].project.name
        <a asp-page="Create" asp-route-projectId="@Model.pageProjectId">Add Data</a>
        </p>
    }
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model._ge_data[0].filename)
            </th>
            <th>
                @Html.DisplayNameFor(model => model._ge_data[0].description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model._ge_data[0].createdDT)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model._ge_data[0].filesize)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model._ge_data[0].pstatus)
            </th>
            </tr>
    </thead>
    <tbody>
    @foreach (var item in Model._ge_data) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.filename)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.createdDT)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.filesize)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.pstatus)
            </td>
            <td> 
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a>
                 <text> | </text>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> 
                 <text> | </text>
                <a asp-controller="ge_file" asp-action="Get" asp-route-id=@item.Id>Download</a>
                 <text> | </text>
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            @if (item.fileext == ".ags") {
                <text> | </text>
                <a asp-controller="ge_ags" asp-action="Get" asp-route-id=@item.Id>Create XML</a>
            }
             @if (item.fileext == ".xml") {
                <text> | </text>
                 <a asp-page="../Transform/Create" asp-route-id="@item.project.Id">Create Transform</a>
            }
            </td>
        
        </tr>
    }
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-page="./Index"
    asp-route-pageOrder="@(Model.pageSort)"
    asp-route-pageIndex="@(Model.pageIndex - 1)"
    asp-route-pageSize="@(Model.pageSize)"
    asp-route-pageFilter="@(Model.pageFilter)"
    asp-route-pageOfficeId="@(Model.pageOfficeId)"
    asp-route-pageProjectId="@(Model.pageProjectId)"
    asp-route-pageUserId="@(Model.pageUserId)"
    class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-page="./Index"
    asp-route-pageOrder="@(Model.pageSort)"
    asp-route-pageIndex="@(Model.pageIndex + 1)"
    asp-route-pageSize="@(Model.pageSize)"
    asp-route-pageFilter="@(Model.pageFilter)"
    asp-route-pageOfficeId="@(Model.pageOfficeId)"
    asp-route-pageProjectId="@(Model.pageProjectId)"
    asp-route-pageUserId="@(Model.pageUserId)"
    class="btn btn-default @nextDisabled">
    Next
</a>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}